import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import AboutUs from '../components/aboutUs'
import Button from '../components/button'
import ProductItem from '../components/productItem'
import ReviewItem from '../components/reviewItem'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <header className={styles.header}>
          <div className={styles.header_text}>
            <h1>Juicy Kotas</h1>
            <h2>Fast food for Fast Times</h2>
            <div className={styles.call_to_action}>
              <Link href={'/order'}><Button title='Order Now'/></Link>
              <Link href={'/contact'}>
                <p>Contact Us</p>
              </Link>
            </div>
          </div>
          <Image src={'/img/products/kota.png'} width={500} height={500}/>
        </header>
        <section>
          <h1>About Us</h1>
        <AboutUs/>
        </section>
        <section>
          <h1>Best Sellers</h1>
          <div className={styles.products}>
            <ProductItem id={1} image='/img/products/burger.png' intro='Chimoko dheng kupindura Ndokubva ndatanga kukungura Yedu yekusada kupfuurwa nezvinhu Ko, Kakandifumura?' preview={false} title='Burger' price={30}/>
            <ProductItem id={1} image='/img/products/burger.png' intro='Chimoko dheng kupindura Ndokubva ndatanga kukungura Yedu yekusada kupfuurwa nezvinhu Ko, Kakandifumura?' preview={false} title='Burger' price={30}/>
            <ProductItem id={1} image='/img/products/burger.png' intro='Chimoko dheng kupindura Ndokubva ndatanga kukungura Yedu yekusada kupfuurwa nezvinhu Ko, Kakandifumura?' preview={false} title='Burger' price={30}/>
          </div>
        </section>
        <section>
          <h1>What Our Customers are Saying</h1>
          <ReviewItem image='/img/janice.png' rating={3} review='Chimoko dheng kupindura Ndokubva ndatanga kukungura Yedu yekusada kupfuurwa nezvinhu Ko, Kakandifumura?' reviewer='Janice'/>
        </section>
        <section>
          <h1>What Are You Waiting For</h1>
          <div className={styles.call_to_action}>
              <Link href={'/order'}><Button title='Order Now'/></Link>
              <Link href={'/contact'}>
                <p>Contact Us</p>
              </Link>
            </div>
        </section>
      </main>
    </div>
  )
}

export default Home
